### ISSUE TITLE
paper对比实验中的询问

### ISSUE THREAD

**Issue by 21-10-4** [mileswyn/SAMIHS#2]
![image](https://github.com/mileswyn/SAMIHS/assets/91857689/dab9f154-b409-42c5-b260-09c55dbee247)
我是一名初学者，我很好奇论文中不同method进行比较时，哪些是基于BCIHM、Instance数据集重新训练的，哪些又是直接采用原作者提供的权重的？
像SAM，它的图片输入是1024，而SAMUS的图片输入是512，这些配置会如何处理？
还有不同的method，它们的一些学习率等超参，warmup和优化器等训练策略会保持一致吗？
非常期待您的回复

**Comment by mileswyn** [comment]
Thanks for your interest~
U-Net, Att-UNet, U-Net++, and H2former, are trained from scratch.
TransUNet and TransFuse are trained with the checkpoints provided by their authors.
SAM and MedSAM are directly tested without fine-tuning.
SAMed, SAMUS, MSA are fine-tuned following their code repos and the descriptions of their papers.

As for the size of input image, you could follow the instructions and codes of SAM and SAMUS. 
We compared these methods with the lr and optimizers claimed in their papers.
If you have further issues about our work, welcome to add comments or send emails to me. (wangyinuo@buaa.edu.cn)

**Comment by 21-10-4** [comment]
非常感谢你的回复~
